server:
  port: 7020

spring:
  application:
    name: DocParser
  ai:
    model:
      chat: ollama
    ollama:
      chat:
        options:
          model: deepseek-r1:1.5b
    vectorstore:
      qdrant:
        initialize-schema: true